import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import AuthProvider from "@/app/components/dashboard/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import App from "@/app/App";

const quickSand = localFont({
  src: [
    {
      path: './fonts/Quicksand-Light.ttf',
      weight: '300',
    },
    {
      path: './fonts/Quicksand-Regular.ttf',
      weight: '400',
    },
    {
      path: './fonts/Quicksand-Medium.ttf',
      weight: '500',
    },
    {
      path: './fonts/Quicksand-SemiBold.ttf',
      weight: '600',
    },
    {
      path: './fonts/Quicksand-Bold.ttf',
      weight: '700',
    },
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quickSand.className}`} suppressHydrationWarning>
        <AuthProvider>
          <App>
            {children}
          </App>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
