import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";


const roboto = localFont({
  src: [
    {
      path: './font/Roboto-Light.ttf',
      weight: '300',
    },
    {
      path: './font/Roboto-Regular.ttf',
      weight: '400',
    },
    {
      path: './font/Roboto-Italic.ttf',
      weight: '400',
      style: 'italic',
    },
    {
      path: './font/Roboto-Medium.ttf',
      weight: '500',
    },
    {
      path: './font/Roboto-SemiBold.ttf',
      weight: '600',
    },
    {
      path: './font/Roboto-Bold.ttf',
      weight: '700',
    },
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className}`} suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
